using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Printing;
using System.Windows;
using System.Windows.Documents;
using System.Windows.Xps;
using System.Windows.Xps.Packaging;
using MySql.Data.MySqlClient;
using SPTC_APP.Database;
using SPTC_APP.Objects;
using SPTC_APP.View;
using SPTC_APP.View.Controls;
using Table = SPTC_APP.Database.Table;

namespace SPTC_APP.View.Pages.Output
{
    public partial class ListReport : Window
    {
        public static string PAYMENTS = $"SELECT * FROM {Table.PAYMENT_DETAILS}";



        private readonly string _query;

        int pagenumber;
        int itemcount = 25;

        public ListReport(string query)
        {
            InitializeComponent();
            _query = query;
            
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="filename">used in both title and printxps</param>
        /// <param name="description">Use "(page)" to substitute for pagenumber</param>
        /// <param name="columns"></param>
        public void StartPrint(string filename,string description, List<ColumnConfiguration> columns)
        {
            pagenumber = 0;
            while (true)
            {
                DataTable dataSource = GetYourData(_query, pagenumber, itemcount);

                if (dataSource.Rows.Count == 0)
                {
                    ControlWindow.ShowStatic("Print Success", $"{filename} is printed", Icons.NOTIFY);
                    this.Close();
                    break;
                }
                this.Show();
                lblDescription.Content = $"Description: {description}".Replace("(page)", (pagenumber+1).ToString());
                lblTitle.Content = "SPTC REPORT: " + filename.ToUpper();
                lblProfile.Content = $"Generated by: {AppState.USER?.name?.ToString() ?? ""} (SPTC {AppState.USER?.position?.title?.ToString() ?? ""})";
                lblFooter.Content = $"SPTC REPORT: {DateTime.Now.ToString("MMMM dd, yyyy")}       Page: {pagenumber + 1}";

                listGrid.ItemsSource = dataSource.DefaultView;
                new DataGridHelper<Object>(listGrid, columns, true);

                if (!ControlWindow.ShowTwoway("Printing", $"Do you want to continue printing \nPage: {pagenumber + 1} of {filename}", Icons.NOTIFY))
                {
                    break;
                }
                
                Print(filename);

                pagenumber++;
            }
        }


        private DataTable GetYourData(string query, int page, int count)
        {
            DataTable dataTable = new DataTable();

            int offset = page * count;

            query = $"{query} LIMIT {offset}, {count};";

            using (MySqlConnection connection = DatabaseConnection.GetConnection())
            {
                connection.Open();

                using (MySqlDataAdapter adapter = new MySqlDataAdapter(query, connection))
                {
                    adapter.Fill(dataTable);
                }
            }

            return dataTable;
        }


        private void Print(string filename)
        {
            string outputPath = AppState.OUTPUT_PATH + filename + ".xps";

            if (!Directory.Exists(AppState.OUTPUT_PATH))
            {
                Directory.CreateDirectory(AppState.OUTPUT_PATH);
            }

            using (XpsDocument xpsDoc = new XpsDocument(outputPath, FileAccess.Write))
            {
                XpsDocumentWriter xpsWriter = XpsDocument.CreateXpsDocumentWriter(xpsDoc);

                PrintTicket printTicket = new PrintTicket();
                printTicket.PageOrientation = PageOrientation.Landscape;
                xpsWriter.Write(reportpage, printTicket);
            }
            this.Hide();

            System.Windows.Controls.PrintDialog printDialog = new System.Windows.Controls.PrintDialog();
            if (printDialog.ShowDialog() == true)
            {
                XpsDocument xpsDocToPrint = new XpsDocument(outputPath, FileAccess.Read);
                FixedDocumentSequence fixedDocumentSequence = xpsDocToPrint.GetFixedDocumentSequence();

                // Get a paginator for the document sequence
                DocumentPaginator paginator = fixedDocumentSequence.DocumentPaginator;

                // Print the paginator
                printDialog.PrintDocument(paginator, "Printing SPTC Report");
                xpsDocToPrint.Close();
            }
        }


    }
}
